# Generated by Django 3.2.7 on 2021-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_paid_ammount_order_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_amount',
            new_name='vendor_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
